## code to prepare `cc_valid_fields_fb_video_insights` dataset goes here
# https://developers.facebook.com/docs/graph-api/reference/video/video_insights/

cc_valid_fields_fb_video_insights <- c(
  # reels
  "blue_reels_play_count",
  "post_impressions_unique",
  "post_video_avg_time_watched",
  "post_video_likes_by_reaction_type",
  "post_video_social_actions",
  "post_video_view_time",

  # video
  "total_video_views",
  "total_video_views_unique",
  "total_video_views_autoplayed",
  "total_video_views_clicked_to_play",
  "total_video_views_organic",
  "total_video_views_organic_unique",
  "total_video_views_paid",
  "total_video_views_paid_unique",
  "total_video_views_sound_on",
  "total_video_complete_views",
  "total_video_complete_views_unique",
  "total_video_complete_views_auto_played",
  "total_video_complete_views_clicked_to_play",
  "total_video_complete_views_organic",
  "total_video_complete_views_organic_unique",
  "total_video_complete_views_paid",
  "total_video_complete_views_paid_unique",
  "total_video_10s_views",
  "total_video_10s_views_unique",
  "total_video_10s_views_auto_played",
  "total_video_10s_views_clicked_to_play",
  "total_video_10s_views_organic",
  "total_video_10s_views_paid",
  "total_video_10s_views_sound_on",
  "total_video_15s_views",
  "total_video_60s_excludes_shorter_views",
  "total_video_retention_graph",
  "total_video_retention_graph_autoplayed",
  "total_video_retention_graph_clicked_to_play",
  "total_video_avg_time_watched",
  "total_video_view_total_time",
  "total_video_view_total_time_organic",
  "total_video_view_total_time_paid",
  "total_video_impressions",
  "total_video_impressions_unique",
  "total_video_impressions_paid_unique",
  "total_video_impressions_paid",
  "total_video_impressions_organic_unique",
  "total_video_impressions_organic",
  "total_video_impressions_viral_unique",
  "total_video_impressions_viral",
  "total_video_impressions_fan_unique",
  "total_video_impressions_fan",
  "total_video_impressions_fan_paid_unique",
  "total_video_impressions_fan_paid",
  "total_video_stories_by_action_type",
  "total_video_reactions_by_type_total",
  "total_video_view_time_by_age_bucket_and_gender",
  "total_video_view_time_by_region_id",
  "total_video_views_by_distribution_type",
  "total_video_view_time_by_distribution_type"
)

usethis::use_data(cc_valid_fields_fb_video_insights, overwrite = TRUE)
